name: gf
channels:
- conda-forge
dependencies:
- basemap
- basemap-data-hires
- branca
- descartes
- fiona
- folium<0.5.9
- gdal
- h5py
- lxml
- markdown
- matplotlib
- numpy
- obspy
- pandas
- pelican
- pytables
- pytest
- pytest-cov
- pytest-mpl
- pytest-faulthandler
- python=3.5
- pyyaml
- rasterio
- scipy
- scikit-learn
- scikit-image
- shapely
- mapio
- impactutils
- libcomcat
